[package]
name = "bit-mite"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
serde_json = "1.0.141"
sha1_smol = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
url = "2.2"
percent-encoding = "2.1"
rand = "0.8"

