[package]
name = "bit-mite"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
urlencoding = "2.1"
reqwest = { version = "0.12", features = ["blocking"] } 
rand = "0.8" 
thiserror = "1.0"

